language: erlang

before_script:
    - "./travis-ci-setup -h127.0.0.1 -utravis"
    - make

# once #89 is closed, this should be replaced by 'make all-test'
script: "make test"
otp_release:
   - 17.0-rc1
   - R16B03-1
   - R16B
   - R15B03
   - R14B04
